apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: run-simple-pipeline
  labels:
    app: devops-knative
spec:
  pipelineRef:
    name: simple-pipeline
  trigger:
    type: manual
  serviceAccount: default
  resources:
  - name: git-source
    resourceRef:
      name: git-source
  - name: docker-image
    resourceRef:
      name: docker-image
